spring:
    application:
        name: ca-project

management:
    endpoints:
        web:
            exposure:
                include: health, info

server:
    port: 8080

cloud:
    aws:
        s3:
            bucket: ca-project-hong2ee2-files

# AWS Region
spring.cloud.aws.region.static=ap-northeast-2

# ?? ??? ?? ??
spring.servlet.multipart.max-file-size=10MB